service:
    name: backup-mysql-util

package:
    individually: true
    exclude:
        - test/**

provider:
    name: aws
    stage: dev
    runtime: nodejs12.x
    region: us-east-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          Resource:
              - "*"
        - Effect: Allow
          Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketVersions
          Resource:
              - "*"
    memorySize: 256
    timeout: 120
    environment:
        DB_HOST: your_database_host_address
        DB_PORT: 3306
        DB_USER: your_database_user
        DB_PASSWORD: your_database_password
        DB_NAME: your_database_name
        BUCKET_NAME: your_bucket_name
resources:
    Resources:
        Bucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:provider.environment.BUCKET_NAME}
                LifecycleConfiguration:
                    Rules:
                        - ExpirationInDays: 90
                          Status: Enabled

functions:
    main: 
        handler: lambda.handler
        name: backup-mysql-util
        events:
            - schedule: rate(1 day)
